---
title: "Presence-Only Prediction - Literature Review"
author: "Benton Tripp"
editor: source
format:
  docx:
    toc: false
    number-sections: false
    highlight-style: github
---

## Abstract

*TODO: Add references*

The continuous development and diversification of species distribution models (SDMs) necessitates a comprehensive examination of both conventional and emerging techniques. This literature review focuses on the application of presence-only prediction techniques, including Poisson point processes and MaxEnt, in the context of bird species distribution modeling. The review seeks to critically analyze the performance of traditional machine learning models such as xgboost, logistic regression, and random forests against the more specialized presence-only prediction techniques (Zhang et al., 2019; Valavi et al., 2021). Moreover, the exploration of Bayesian methods, data processing mechanisms, and innovative sampling methodologies aims to shed light on strategies to enhance model performance and reduce bias. The overarching goal of this review is to provide a systematic foundation for further research into the integration and optimization of various modeling strategies for presence-only predictions.

## Introduction
        
### Background and Significance

Species distribution modeling (SDM) has become increasingly crucial in the realm of ecological research. Driven by advancements in technology, remote sensing, and computational capabilities, there has been a proliferation of methods to predict species distributions (Renner & Warton, 2013; Marmion et al., 2008; O'Sullivan and Unwin, 2010). These models often center around unique datasets, such as presence-only data, which poses unique challenges for statistical modeling due to inherent uncertainty from data censoring and specific sampling procedures.

In the context of presence-only data, earlier modeling techniques primarily focused on measuring environmental similarities. Contemporary methods, however, emphasize modeling species' suitability in relation to the surrounding environment. This is accomplished by leveraging what is known as "background" or "pseudo-absence" data—specific locations within the study area where a species' presence is unconfirmed but which represent a spectrum of environmental conditions (Busby 1991, Carpenter et al. 1993; Phillips et al., 2009b).

In modeling presence-only data, certain strategies have remained prominent and evolved through continued research. Poisson point processes, within likelihood and Bayesian contexts, model solely using presence points and environmental covariates, eliminating the need for absence or pseudo-absence points. Conversely, logistic regression and Maximum Entropy utilize both observations and pseudo-absence points as binary indicators, incorporating environmental and temporal variables as predictors (Warton & Shepherd, 2010; Chakraborty et al., 2011; Ward et al., 2009; Dorazio, 2012).

*TODO: add references*

Recently, traditional machine learning models such as Random Forests, Support Vector Machines, and Gradient Boosting Machines have also been adopted for presence-only data modeling, using "pseudo-absence" points to determine species' distributions. These algorithms detect complex, non-linear relationships in the data, enhancing predictions of species occurrences. Through ensemble methods or kernel-based strategies, they effectively capture the nuanced patterns and interactions inherent in ecological datasets.

While traditional machine learning models have gained traction in recent years, Bayesian approaches offer another layer of sophistication. Bayesian models are recognized for their ability to address the complexities and uncertainties characteristic of presence-only data. Key techniques in Bayesian modeling include Markov Chain Monte Carlo (MCMC) and the Integrated Nested Laplace Approximation with Stochastic Partial Differential Equation (INLA-SPDE). Though MCMC is a proven method, INLA-SPDE offers a more efficient computational framework. Both strategies deliver models that enable precise quantification of uncertainties (Divino, 2013; Lezama-Ochoa et al., 2020).

### Objective of the Literature Review

The objective of this review is to critically evaluate and synthesize the developments in presence-only prediction techniques. The exploration aims to shed light on the performance of traditional machine learning models against more specialized techniques, diving deep into the nuances of Bayesian methods, presence-only data processing mechanisms, and innovative sampling methodologies.

## Pseudo-Absence Data in Presence-Only Models

### Pseudo-absence Selection Strategies

The selection of pseudo-absence data directly impacts the accuracy and reliability of presence-only models. Before discussing primary methods and models in subsequent sections, understanding the intricacies of pseudo-absence selection is essential.

Wisz and Guisan (2009) assessed the impacts of different pseudo-absence selection strategies on species distribution models and their predictions. Specifically, they examined the use of (a) real absences, (b) pseudo-absences randomly chosen from the background, and (c) a two-step approach using pseudo-absences from low suitability regions predicted by Ecological Niche Factor Analysis (ENFA) or BIOCLIM. The study highlighted that while logistic regression modelling (LRM) has been a popular choice for predicting potential species distributions, its dependency on absence data has limited its applicability, especially when studying species with insufficient absence data. Wisz and Guisan (2009) further distinguished between two key techniques for relating field observations to environmental predictor variables. The "profile techniques" use data documenting only the species presence and include methods like BIOCLIM, DOMAIN, and ENFA. On the other hand, "group discrimination techniques" require both presence and absence data, with logistic regression modelling (LRM), a subset of generalized linear models (GLM), being a prevalent approach. However, due to the inherent challenges associated with the absence of data in many species distribution studies, pseudo-absences are often used. One identified concern with random pseudo-absences is their potential overlap with actual species presence locations, leading to potential model inaccuracies.

In a notable two-step modeling example, Engler et al. used the profile technique "ENFA" to map habitat suitability and then selected pseudo-absences from low suitability areas. These pseudo-absences were then integrated into a subsequent logistic regression model to forecast the species' potential distribution. However, Wisz and Guisan (2009) found that two-step modeling approaches often received weak support from data. Using a virtual species approach, which defines a species' distribution *a priori*, the study demonstrated that models based on randomly selected pseudo-absences, despite having lower fit to training data, showed superior predictive power and variable selection over the two-step methods. It was suggested that two-step pseudo-absences tend to result in overfit models, which while they might better fit the training data, lose generality and thus have reduced predictive power on independent samples.

Furthermore, the study accentuated the importance of parsimony in model selection. Contrary to methods like BIOCLIM and ENFA, which lack a mechanism for predictor selection and can't incorporate quadratic relationships to predictors, parsimonious models (with fewer predictor variables) are believed to offer better predictive power. As an example, models like MAXENT, which calibrate complexity based on sample size, often outperform models that employ intricate response shapes irrespective of sample size. Ultimately, the rigorous model selection process, aiming to select the most pertinent predictors and accurate parameter estimates, remains paramount in the modeling procedure (Wisz & Guisan, 2009).

Senay et al. (2013) delved deeper into the realm of pseudo-absence selection, specifically for spatial distribution models (SDMs). As the field continues to expand, a multitude of techniques have emerged, each with varied results concerning their efficacy. Noting the paramount importance of both presence and absence data in generating reliable SDM predictions, Senay et al. emphasized the demand for a method that seamlessly integrates both geographical and environmental aspects. This would ideally lead to pseudo-absence points representative in both realms.

In response to this demand, Senay et al. (2013) introduced a distinctive three-tiered methodology. The inaugural step focuses on defining a geographically appropriate boundary around species presence points. This is achieved by analyzing environmental variables across varied distances, ensuring that the boundary isn't determined by an arbitrary radius alone. The next phase pinpoints areas that are environmentally distinct from known presence points, yet remain within the earlier specified distance boundary. In the concluding step, K-means clustering is utilized to filter potential pseudo-absences. The centroids of clusters, which are environmentally distinct as ascertained in the second step, are prioritized.

The significance of SDMs cannot be understated. These models have found critical applications in forecasting species distributions for conservation efforts, biocontrol introductions, and especially in assessing the potential spread of invasive species. Their rise in popularity can largely be attributed to the convergence of enhanced data availability and the strides in computational capability. At their core, SDMs predict species' distributions based on their observed environmental niche from known presence locations. While mechanistic or process-driven models offer a valuable alternative, they demand a profound grasp of a species' environmental and physiological needs, which isn't always viable. A prevalent concern regarding SDMs is their accuracy, especially when absence data is sparse or unreliable. Senay et al. addressed this concern by spotlighting the challenges in discerning genuine absences, which could be masked by factors like undetected species presence, natural obstructions, or even short-term migration patterns (Jime´nez-Valverde et al, 2008; Phillips et al., 2006; Lobo et al., 2010; Peterson, 2006; Kearney & Porter, 2009; Wisz & Guisan, 2009; Soberon & Peterson, 2005).

To bridge the gap presented by the scarcity of absence data, Senay et al. categorized the primary modeling approaches into three distinct groups: basic presence-only models, enhanced presence-only models, and the comprehensive presence-absence models. The basic models utilize only presence data to sketch species distributions, while their enhanced counterparts integrate these data with pivotal background environmental variables, as seen in models such as MaxEnt, ENFA, and PBL. The presence-absence models incorporate both data types to predict habitat suitability or overall species distribution. In scenarios where genuine absence data is lacking, these models often rely on the generation of pseudo-absence points. The range of these models spans from traditional regression-based ones, like GLM and GAM, to cutting-edge machine learning algorithms such as ANN, SVM, and naïve Bayes. Concluding their discussion, the authors detailed the three primary pseudo-absence selection techniques: random selection, geographically constrained selection, and those anchored in environmental considerations, with the latter gaining traction due to its proven enhanced precision (Hirzel et al., 2002; Li et al., 2011; Elith et al., 2006; Lorena et al., 2011; Chefauoui & Lobo, 2008; Warton & Shepherd, 2010; Hengl, 2009).

## Presence/Absence vs. Presence-Only Data

Building on the complexities of pseudo-absence selection, it's crucial to dissect the differences between presence/absence and presence-only data as these distinctions have important implications. Gelfand (2018) explores these nuances, emphasizing the contrasting characteristics between the two data types. Notably, the locations are fixed under presence/absence data, whereas they are random for presence-only data. This distinction creates an incompatibility in defining the "probability of presence" between the two types. Contrary to the assertions in previous literature which suggests that presence/absence modeling can be derived from presence-only specifications (Dorazio, 2014; Royle et al., 2012; Hastie and Fithian, 2013), and that fusion of the two data types can be easily executed (Pacifici et al., 2017), Gelfand argues otherwise. He recommends modeling presence/absence data at the point level, requiring the specification of two surfaces. One surface gives the probability of presence at any location, while the second, a realization from the first, provides a binary map yielding the results of Bernoulli trials at all locations, which is only partially observed. In contrast, presence-only data should be modeled using a (partially observed) point pattern, emerging from a random count of individuals seen at random locations, steered by an intensity function specification, with no association to Bernoulli trials but rather with areas.

Furthermore, Gelfand (2018) underscores the need for coherent modeling in species distribution studies. The presence-only perspective provides for intensities through point patterns, leading to intensity surfaces that can be converted to density surfaces. These surfaces express the relative likelihood of observing a species at one location versus another but do not equate to a probability of presence surface. He delves into the technicalities of presence probability, noting that equating probability of presence to “one or more” sightings of a species can lead to local distortion (Aarts et al., 2012). The probability of presence does not discern between a single or multiple observations within a given set.

Building on this, Gelfland discusses the complexities of species distribution within a specified region, noting the finite presence in any bounded area. Consequently, presence cannot be simply dimensionalized at a point but can be point-referenced in observations. At point-level, the presence/absence surface over a region manifests as distinct "patches" where a species is found. These patches, from an ecological perspective, can be visualized as dense collections of individuals of a specific species, with absences being distinguished by sufficiently large gaps. Importantly, presence/absence is seen as a local phenomenon, suggesting that if presence is noted at a location $s$, then it is also present throughout a sufficiently small neighborhood, $\delta s$, of $s$. Consequently, the actual presence/absence surface remains locally constant, taking value 1 in a patch and 0 otherwise.

Gelfand (2018) calls for a more meticulous approach to modeling when studying species distributions. Recognizing and accounting for the inherent incompatibilities between data types is pivotal to ensure accurate inference.

## Strategies to Address Bias

## MaxEnt and Poisson Point Processes in Species Distribution Modeling

### Theoretical Underpinnings

Maximum Entropy (MaxEnt) and Poisson Point Processes (PPMs) have been identified as essential tools for species distribution modeling (SDM). The appeal of SDM lies in its potential to address significant questions, such as the impact of climate change on species distributions. Recent advancements in remote sensing, GIS, and computational power have further facilitated the development of these models (Renner & Warton, 2013; Thullier et al., 2008; O'Sullivan and Unwin, 2010).

MaxEnt models the probability per grid cell and analyzes data after aggregating them into presence/absence grid cells. In contrast, a Poisson PPM models the limiting expected count or intensity per unit area, rather than per grid cell. This per area basis, compared to per grid cell, is a significant distinction between the two approaches (Renner & Warton, 2013).

Interestingly, Renner & Warton (2013) highlight the mathematical equivalence of the MaxEnt procedure and Poisson regression, asserting that both approaches fit the same model and estimate parameters to maximize the same function up to a constant. Moreover, the MaxEnt and PPM solutions for grid cell data are proportional, with identical estimates of slope parameters.

### Applications and Limitations

MaxEnt's applications are sometimes hindered by its shortcomings. It lacks clarity regarding diagnostic tools to assess model fit and is unclear about the spatial resolution when constructing grid cells (Renner & Warton, 2013).

A key limitation of MaxEnt is its scale dependence of predicted probabilities and arbitrary choice of spatial resolution. The per grid cell analysis is not invariant under choice of spatial resolution, unlike PPM, which models intensity on a per area basis (Renner & Warton, 2013). MaxEnt also fails to estimate the intercept consistently, diverging to −∞ as spatial resolution increases (Renner & Warton, 2013; Elith et al., 2011).

PPM, on the other hand, offers various solutions to MaxEnt's problems. Predicted intensities in PPM are scale-invariant, and spatial resolution can be increased until log-likelihood converges. Various goodness-of-fit procedures are available for PPM, enabling more robust model adequacy assessment (Renner & Warton, 2013; Cressie, 1993; Baddeley et al., 2005).

Warton & Shepherd (2010) introduce PPMs as an alternative to pseudo-absence approaches, which have weaknesses in model specification, interpretation, and implementation. Point process modeling directly addresses these concerns, proposing a more sound specification for observed data without needing to generate new data. PPM also provides a framework for the selection of pseudo-absences, an area often tackled ad hoc in ecology (Warton & Shepherd, 2010).

### Insights into Presence-Only Prediction

Presence-only prediction is a critical aspect of species distribution modeling. MaxEnt is limited in this regard due to its scale dependence and the current ambiguity over the spatial resolution (Renner & Warton, 2013).

PPM is proposed as a solution to the "pseudo-absence problem" in presence-only data, providing a more robust specification, clearer interpretation, and structured implementation than MaxEnt. The problems related to the pseudo-absence approach, specifically those associated with model specification, interpretation, and implementation, are rectified through the application of a point process modeling framework (Warton & Shepherd, 2010). Various authors have addressed the confusion over how pseudo-absences should be chosen (Elith and Leathwick, 2007; Guisan et al., 2007; Zarnetske, Edwards, and Moisen, 2007; Phillips et al., 2009), recognizing that the selection method can yield different outcomes (Chefaoui and Lobo, 2008).

Studies have demonstrated that logistic regression slope parameters and their corresponding standard errors converge to those of the Poisson point process model as the number of pseudo-absences is increased (Warton & Shepherd, 2010). This demonstrates that the PPM approach successfully addresses the arbitrary nature of pseudo-absence selection, signifying that a specific form of point process model is being estimated, even in the utilization of pseudo-absence methods. Current selection procedures for pseudo-absences do not align with best practices, as they are frequently chosen at random and lack a basis in convergence criteria (Pearce and Boyce, 2006; Zarnetske, Edwards, and Moisen, 2007).

The exploration of MaxEnt and PPM in species distribution modeling reveals intriguing similarities and critical differences between these two methods. While MaxEnt is challenged by its shortcomings, including scale dependence and lack of consistent intercept estimation, PPM offers robust solutions, especially for presence-only prediction. The equivalence between MaxEnt and PPM and the insights into the pseudo-absence problem signify a notable contribution to ecological modeling, pointing to the potential for further refinements and innovations in the field.

## Machine Learning Models for Species Distribution Modeling

Zhang et al. (2019) expound on the power of the Random Forests (RF) as a Species Distribution Model (SDM) algorithm. At its core, RF is an ensemble learning technique designed to produce both categorical and numerical species distribution maps, a feat achieved using the classification tree (CT) and regression tree (RT) algorithms respectively (Strobl et al., 2009). CT, in its statistical essence, also has the capability to provide probabilistic predictions, known as class probability (Zhang et al., 2019). The quintessence of RF lies in its bootstrap samples which are harnessed to construct a plethora of decision trees, which are then aggregated to predict new data. In the context of CT, model output is often categorical and determined by the proportion of votes, with the ratio for presence in CT potentially being leveraged as a relative index of occurrence or numerical prediction (Strobl et al., 2009).

With an abundance of metrics available for evaluating SDM performance, discerning the most effective one becomes challenging (Fielding & Bell, 1997; Liu et al., 2011). Different metrics invariably have their unique strengths, weaknesses, and methods of weighting prediction errors like omission, commission, or confusion. Emphasizing the importance of utilizing multiple performance metrics, Zhang et al. (2019) underscore the utility of threshold-independent evaluations such as root mean square error (RMSE), mean absolute prediction error (MAE), coefficient of determination (R^2), mean cross entropy (MXE), and several AUC measures. Numerical predictions, in particular, are distinguished by their discrimination capacity, such as AUC values, and reliability metrics, including RMSE, MAE, and R^2 (Liu et al., 2011; Pearce & Ferrier, 2000). The inherent importance of these two facets (reliability and discrimination capacity) is contingent upon the model's application and the user's proficiency level (Pearce & Ferrier, 2000).

A significant challenge emerges when converting numerical predictions to binary predictions, primarily because the optimal threshold is influenced by the choice of threshold-setting method. This choice has palpable ramifications on the estimation of RF model performance and potential species range shifts due to climate change (Zhang et al., 2019). Out of multiple threshold methods explored, Zhang et al. (2019) highlighted four as particularly promising for binary conversions of continuous predictions with presence-only data: MaxKappa, MaxOA, MinROCdist, and MaxTSS. These methods demonstrated consistent performance in threshold determination, model performance, and range shift projection. Notably, the default CT classification method was deemed suboptimal for binary conversions (Zhang et al., 2017).

To conclude, the researchers proposed a detailed procedural framework for harnessing RF methods with presence-only data in modeling species distributions. This framework emphasizes the importance of the RT model when prioritizing model discrimination capacity over reliability, and the converse. While the framework offers a generic concept suited for virtually any model prediction question utilizing presence-only data, its applications might necessitate fine-tuning depending on specific species and contexts, highlighting the diverse nuances of the ecosystem (Zhang et al., 2017).

## Bayesian Approaches in Species Distribution Modeling

### Integrated Nested Laplace Approximation with Stochastic Partial Differential Equation (INLA‑SPDE)

The Integrated Nested Laplace Approximation with Stochastic Partial Differential Equation (INLA-SPDE) framework presents a Bayesian approach for handling the challenges of species distribution modeling (SDM). Bayesian models such as INLA-SPDE are adept at addressing complex datasets laden with spatial and temporal autocorrelations, thus providing an alternative to frequentist approaches, which yield fixed parameter estimates (Lezama-Ochoa et al., 2020; Martínez-Minaya et al., 2018; Blangiardo & Cameletti, 2015).

The INLA-SPDE method excels in capturing both well-known and more marginal areas where species are found, thereby expanding the predictive capacity of SDMs (Lezama-Ochoa et al., 2020). This framework incorporates multilevel structures with spatial random effects, which are stochastic processes indexed in space. This strategy adequately represents the various spatially explicit processes influencing species patterns (Lezama-Ochoa et al., 2020; Pennino et al., 2017; Redding et al., 2017).

One distinct advantage of the INLA-SPDE approach is its utilization of Delaunay triangulation over regular grids commonly used in SDMs. This triangulation congregates additional information in regions with higher density of observations, leading to more accurate predictions (Lezama-Ochoa et al., 2020).

Despite its capabilities, INLA-SPDE faces specific limitations such as difficulties in processing categorical variables and challenges in effective triangulation for analyzing spatial data (Lezama-Ochoa et al., 2020). Furthermore, although it offers a faster computational alternative to Markov Chain Monte Carlo (MCMC) methods, it should not replace MCMC entirely but rather serve as a complementary or alternative approach (Rue et al.; Lezama-Ochoa et al., 2020).

The Bayesian foundation of INLA-SPDE also allows for the explicit quantification of uncertainties, providing credible intervals and standard deviations in addition to point estimates (Lezama-Ochoa et al., 2020). This explicit quantification is particularly vital for management decisions, as it provides a fuller understanding of the model's predictions.

For a holistic understanding of species distribution, it is essential to contrast INLA-SPDE with other SDMs like Random Forests, MaxEnt, and Boosted Regression Trees. Each model carries its unique set of strengths and limitations, warranting careful consideration for effective species management (Lezama-Ochoa et al., 2020).

### Markov Chain Monte Carlo (MCMC)

Divino (2013) dives deep into the intricate nuances of modeling presence-only data, presenting a hierarchically structured Bayesian model tailored for estimating parameters of a linear logistic regression suited to presence-only data. The core objective of this model is to bridge the observed stratum variable $Z$ with covariates  $X$ , even in scenarios where there's a conspicuous absence of a binary response $Y$. The presence of this absence, as Divino highlights, induces dual layers of uncertainty: one emanating from the censoring mechanism and the other from the sampling procedure itself.

Several key equations underscored by Divino (2013) illuminate the mechanics of the model. At the forefront is the presence-only data approximation:

$$ \phi_{\text{pod}}(x) \approx x\beta + \log \left( \frac{n_1 u + np}{n_1 u} \right) $$

This equation serves as a nuanced modification to the conventional linear regression model, sculpting it to align more harmoniously with presence-only datasets. It elegantly blends the regular linear prediction, $x\beta$, with a logarithmic term that serves as a correction factor. Delving further, there are the approximations for the conditional probability of occurrence and the marginal probability $P(Z|C=1, x)$ upon marginalizing over $Y$. These equations are instrumental in capturing the subtleties of presence-only data and its inherent complexities.

At the heart of the Bayesian framework is the Markov Chain Monte Carlo (MCMC) algorithm. Here, Divino (2013) shines a spotlight on the integral role of data augmentation within the MCMC computation. This step, characterized by augmenting the observed dataset to a more amenable distribution, is pivotal. It ensures that at each iteration, a consistent value for $n_1u$ can be derived, essential for fine-tuning the regression function for presence-only data.

Moreover, the MCMC algorithm is laid out in a sequential scheme:

1. Initialization of hyperparameters and latent variables.
2. Calculation of the sum of latent variables to adjust the regression function.
3. Sampling of hyperparameters based on the observed data.
4. Estimation of linear parameters conditional on the hyperparameters.
5. A sampling step for unobserved data in the presence-only framework.

The process, iterative in nature, is reiterated to refine estimates, thereby leveraging the strengths of Bayesian methods.

Divino (2013) summarizes the hierarchical layout for the Bayesian model as follows:

1. At the summit, the hyperparameter $\theta$, governing the distribution of $\beta$, offering flexibility.
2. Descending a level, the linear parameters $\beta$, which illuminate the relationship between the covariates $X$ and the response $Y$.
3. Further down the unobserved data $y_u$ are modeled as latent parameters in a Bernoulli distribution.
4. At the base, the likelihood tethered to the observable variable $Z$.

Through this layered approach, Divino (2013) encapsulates the multiple sources of uncertainty, providing a cohesive structure for handling presence-only data.

Within the realm of academic inquiry, the integration of the Bayesian modeling strategy with the MCMC framework, as articulated by Divino (2013), manifests as a sophisticated and robust approach for analyzing presence-only data. As the relevance of such data intensifies, especially in disciplines such as ecology, Divino's model and methodological paradigm offer a significant reference point for subsequent studies endeavoring to achieve dependable predictions and inferences.

## Discussion

### Synthesis of Findings

### Implications for Future Research

## Conclusion

### Summary of Major Findings

### Recommendations

## References

Aarts, G., J. Fieberg, and J. Matthiopoulos (2012). Comparative interpretation of count, presence/absence and point methods for species distribution models. Methods in Ecology and Evolution 3, 177–187.

Baddeley, A., & Turner, R. (2005). spatstat: An R Package for Analyzing Spatial Point Patterns. Journal of Statistical Software, 12(6). https://doi.org/10.18637/jss.v012.i06

Brieuc, M. S. O., Waters, C. D., Drinana, D. P., & Naish, K. A. (2018). A practical introduction to random forest for genetic association studies in ecology and evolution. Mol. Ecol. Resour., 18, 755–766.

Chefaoui, R. M., & Lobo, J. M. (2008). Assessing the effects of pseudo-absences on predictive distribution model performance. Ecological Modelling, 210(4), 478–486. https://doi.org/10.1016/j.ecolmodel.2007.08.010

Cressie, N. (1993). Statistics for spatial data. In John Wiley & Sons, Inc. eBooks. https://doi.org/10.1002/9781119115151

Divino, F. (2013, May 6). Bayesian modeling and MCMC computation in linear logistic regression for presence-only data. arXiv.org. https://arxiv.org/abs/1305.1232

Dorazio, R. M. (2014). Accounting for imperfect detection and survey bias in statistical analysis of presence-only data. Global Ecology and Biogeography 23, 1472–1484.

Elith J., Graham C. H., Anderson R. P., Dudik M., Ferrier S., et al. (2006) Novel methods improve prediction of species; distributions from occurance data. Ecography 29: 129–151.

Elith, J., & Leathwick, J. R. (2009). Species Distribution Models: Ecological explanation and prediction across space and time. Annual Review of Ecology, Evolution, and Systematics, 40(1), 677–697. https://doi.org/10.1146/annurev.ecolsys.110308.120159

Elith, J., Phillips, S. J., Hastie, T., Dudík, M., Chee, Y. E., & Yates, C. J. (2010). A statistical explanation of MaxEnt for ecologists. Diversity and Distributions, 17(1), 43–57. https://doi.org/10.1111/j.1472-4642.2010.00725.x

Engler, R., Guisan, A., & Rechsteiner, L. (2004). An improved approach for predicting the distribution of rare and endangered species from occurrence and pseudo-absence data. Journal of Applied Ecology, 41(2), 263–274. https://doi.org/10.1111/j.0021-8901.2004.00881.x

Fielding, A. H., & Bell, J. F. (1997). A review of methods for the assessment of prediction errors in conservation presence/absence models. Environ. Conserv., 24, 38–49.

Gelfand, A. E. (2018, September 5). Preferential sampling for presence/absence data and for fusion of presence/absence data with presence-only data. arXiv.org. https://arxiv.org/abs/1809.01322

Guisan, A., Tingley, R., Baumgartner, J. B., Naujokaitis-Lewis, I., Sutcliffe, P., Tulloch, A. I. T., Regan, T. J., Brotons, L., McDonald-Madden, E., Mantyka-Pringle, C., Martin, T. G., Rhodes, J. R., Maggini, R., Setterfield, S. A., Elith, J., Schwartz, M. W., Wintle, B. A., Broennimann, O., Austin, M. P., . . . Buckley, Y. M. (2013). Predicting species distributions for conservation decisions. Ecology Letters, 16(12), 1424–1435. https://doi.org/10.1111/ele.12189

Hastie, T. and W. Fithian (2013). Inference from presence-only data; the ongoing controversy. Ecography 36, 864–867.

Hengl T. (2009) A Practical Guide to Geostatistical Mapping. Open Access Publication. Available: http://spatial-analyst.net/book/system/files/Hengl_ 2009_GEOSTATe2c1w.pdf.

Hirzel A. H., Hausser J., Chessel D, Perrin N (2002) Ecological-Niche factor analysis: How to compute habitat-suitability maps without absence data? Ecology 83: 2027.

Jime´nez-Valverde A., Lobo J. M., Hortal J. (2008) Not as good as they seem: the importance of concepts in species distribution modelling. Diversity and Distributions 14: 885–890.

Kearney M., Porter W. (2009) Mechanistic niche modelling: combining physiological and spatial data to predict species’ ranges. Ecology Letters 12: 334.

Lezama-Ochoa, N., Pennino, M. G., Hall, M., Lopez, J., & Murua, H. (2020). Using a Bayesian modelling approach (INLA-SPDE) to predict the occurrence of the Spinetail Devil Ray (Mobular mobular). Scientific Reports, 10(1). https://doi.org/10.1038/s41598-020-73879-3

Li W., Guo Q., Elkan C. (2011) Can we model the probability of presence of species without absence data? Ecography 34: 1096–1105.

Liu, C., White, M., & Newell, G. (2011). Measuring and comparing the accuracy of species distribution models with presence–absence data. Ecography, 34, 232–243.

Lobo J. M., Jime´nez-Valverde A., Hortal J. (2010) The uncertain nature of absences and their importance in species distribution modelling. Ecography 33: 103–114.

Lorena A. C., Jacintho L. F. O., Siqueira M. F., Giovanni R. D., Lohmann L. G., et al. (2011) Comparing machine learning classifiers in potential distribution modelling. Expert Systems with Applications 38: 5268–5275.

Marmion, M., Hjort, J., Thuiller, W., & Luoto, M. (2008). A comparison of predictive methods in modelling the distribution of periglacial landforms in Finnish Lapland. Earth Surface Processes and Landforms, 33(14), 2241–2254. https://doi.org/10.1002/esp.1695

Martínez-Minaya, J., Cameletti, M., Conesa, D. & Pennino, M. G. Species distribution modeling: a statistical review with focus in spatio-temporal issues. in Stochastic Environmental Research and Risk Assessment 1–18 (2018).

O’Sullivan, D., & Unwin, D. (2010). Geographic Information Analysis. https://doi.org/10.1002/9780470549094

Pacifici, K., B. J. Reich, D. A.W. Miller, B. Gardner, G. Stauffer, S. Singh, A. McKerrow, and J. A. Collazo (2017). Integrating multiple data sources in species distribution modeling: a framework for data fusion. Ecology, 840–850.

Pearce, J., & Boyce, M. S. (2006). Modelling distribution and abundance with presence-only data. Journal of Applied Ecology, 43(3), 405–412. https://doi.org/10.1111/j.1365-2664.2005.01112.x

Pearce, J., & Ferrier, S. (2000). Evaluating the predictive performance of habitat models developed using logistic regression. Ecol. Modell., 133, 225–245.

Pennino, M. G., Vilela, R., Bellido, J. M. & Mendoza, M. Comparing methodological approaches to model occurrence patterns of marine species. in Research Advances in Marine Resources (Eds: Norton, K.). (Nova Publisher, ISBN: 978-1-53612-177-3, 2017).

Peters, J., Baets, B. D., Verhoest, N. E. C., Samson, R., Degroeve, S., Becker, P. D., & Huybrechts, W. (2007). Random forests as a tool for ecohydrological distribution modelling. Ecol. Model., 207, 304–318.

Peterson A. T. (2006) Uses and Requirements of Ecological Niche Models and Related Distributional Models. Biodiversity Informatics 3: 59–72.

Phillips, S. J., Dudík, M., Elith, J., Graham, C. H., Lehmann, A., Leathwick, J. R., & Ferrier, S. (2009). Sample selection bias and presence-only distribution models: implications for background and pseudo-absence data. Ecological Applications, 19(1), 181–197. https://doi.org/10.1890/07-2153.1

Phillips S. J., Anderson R. P., Schapire RE (2006) Maximum entropy modeling of species geographic distributions. Ecological Modelling 190: 231–259.

Redding, D. W., Lucas, T. C., Blackburn, T. M. & Jones, K. E. Evaluating Bayesian spatial methods for modelling species distributions with clumped and restricted occurrence data. PLoS ONE 12, e0187602 (2017).

Renner, I., & Warton, D. I. (2013). Equivalence of MAXENT and Poisson Point process models for species distribution modeling in Ecology. Biometrics, 69(1), 274–281. https://doi.org/10.1111/j.1541-0420.2012.01824.x

Royle, J. A., R. B. Chandler, C. Yackulic, and J. D. Nichols (2012). Likelihood analysis of species occurrence probability from presence-only data for modelling species distributions. Methods in Ecology and Evolution 3, 545–554.

Rue, H., Martino, S. & Chopin, N. Approximate Bayesian inference for latent Gaussian models by using integrated nested Laplace approximations. J. R. Stat. Soc. Ser. B. (Stat. Method.) 71, 319–392 (2009).

Senay SD, Worner SP, Ikeda T (2013) Novel Three-Step Pseudo-Absence Selection Technique for Improved Species Distribution Modelling. PLoSONE 8(8): e71218. doi:10.1371/journal.pone.0071218

Soberon J., Peterson A. T. (2005) Interpretation of models of fundamental ecological niches and species’ distriputional areas. Biodiversity Informatics 2: 1–10.

Strobl, C., Malley, J. D., & Tutz, G. (2009). An introduction to recursive partitioning: Rationale, application and characteristics of Classification and Regression Trees, Bagging and Random Forests. Psychol. Methods, 14, 323–348.

Valavi, R., Guillera-Arroita, G., Lahoz-Monfort, J. J., & Elith, J. (2021). Predictive performance of presence‐only species distribution models: a benchmark study with reproducible code. Ecological Monographs, 92(1). https://doi.org/10.1002/ecm.1486

Wisz, M. S., & Guisan, A. (2009). Do pseudo-absence selection strategies influence species distribution models and their predictions? An information-theoretic approach based on simulated data. BMC Ecology, 9(1), 8. https://doi.org/10.1186/1472-6785-9-8

Warton, D. I., & Shepherd, L. (2010). Poisson point process models solve the “pseudo-absence problem” for presence-only data in ecology. The Annals of Applied Statistics, 4(3). https://doi.org/10.1214/10-aoas331

Zarnetske, P. L., Edwards, T. C., & Moisen, G. G. (2007). HABITAT CLASSIFICATION MODELING WITH INCOMPLETE DATA: PUSHING THE HABITAT ENVELOPE. Ecological Applications, 17(6), 1714–1726. https://doi.org/10.1890/06-1312.1

Zhang, L., Huettmann, F., Zhang, X., Liu, S., Park, S., Yu, Z., & Mi, C. (2019). The use of classification and regression algorithms using the random forests method with presence-only data to model species’ distribution. MethodsX, 6, 2281–2292. https://doi.org/10.1016/j.mex.2019.09.035

Zhang, L., Wang, L., Liu, S., Sun, P., Yu, Z., Huang, S., & Zhang, X. (2017). An evaluation of four threshold selection methods in species occurrence modelling with random forest: case studies with Davidia involucrata and Cunninghamia lanceolata. Chin. J. Plant Ecol., 41, 387–395.
